{
 "title": "Bulkhead pattern, scenario I",
 "time": { "from": "2022-07-30T00:20:40.000Z", "to": "2022-07-30T00:21:40.000Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "t/s S1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "transactions",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "request_service1_counted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "tomcat conections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connections_current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "thread busy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_threads_busy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "thread config max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_threads_config_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "avg process time per request",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request_service1_timed",
     "query": "SELECT \"count\" FROM \"request_service1_timed\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "avg process time per request",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request_service2_timed",
     "query": "SELECT \"count\" FROM \"request_service1_timed\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "t/s Err",
   "type": "gauge",
   "description": "The number of transaction that are rejected due to Bulkhead is full.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service1_bulkheadFullException_counted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service 3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "avg process time per request",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request_service3_timed",
     "query": "SELECT mean(\"mean\") FROM \"request_service3_timed\" WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service 4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "avg process time per request",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request_service4_timed",
     "query": "SELECT mean(\"mean\") FROM \"request_service3_timed\" WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "t/s S3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "transactions",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "request_service3_counted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}