resilience4j.bulkhead:
  instances:
    Case1:
      maxConcurrentCalls: 4
      maxWaitDuration: 10ms
       
            
resilience4j.thread-pool-bulkhead:
    instances:
        Test2:
            coreThreadPoolSize: 4
            maxThreadPoolSize: 4
            queueCapacity: 1
            
            