resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 60000
      
      #when 60 percentage of request fail the circuit changes to open
      failureRateThreshold: 60 
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
  instances:
    Service1:
      baseConfig: default
      
resilience4j.thread-pool-bulkhead:
    instances:
        Service2:
            maxThreadPoolSize: 2
            coreThreadPoolSize: 1
            queueCapacity: 1

resilience4j.bulkhead:
    instances:
        Service2b:
            maxConcurrentCalls: 2
            maxWaitDuration: 10ms