resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 60000
      
      #when 60 percentage of request fail the circuit changes to open
      failureRateThreshold: 60 
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
  instances:
    Service1:
      baseConfig: default
      
resilience4j.bulkhead:
    instances:
        Service1:
            maxConcurrentCalls: 2
            maxWaitDuration: 10ms
        Test1:
            maxConcurrentCalls: 4
            maxWaitDuration: 10ms
            
resilience4j.thread-pool-bulkhead:
    instances:
        Test2:
            coreThreadPoolSize: 4
            maxThreadPoolSize: 4
            queueCapacity: 1
            
            